# Generated by Django 3.2.9 on 2021-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_required_day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
